# CodeQL configuration file (Java)

disable-default-queries: false  # disable all default queries, because we are going to override one of them
#packs:
#  java:
#    - zbazztian/sebastians-query-pack
